---------------- 삭제 --------------------------------

DROP SEQUENCE EOB_APPLICANT_SEQ;
DROP SEQUENCE EOB_EVENT_SEQ;
DROP SEQUENCE EOB_JOIN_SEQ;

ALTER TABLE EOB_JOIN DROP CONSTRAINT FK_EOB_EVENT_TO_EOB_JOIN;
ALTER TABLE EOB_JOIN DROP CONSTRAINT FK_EOB_APPLICANT_TO_EOB_JOIN;

DROP TABLE EOB_APPLICANT;
DROP TABLE EOB_ADMIN;
DROP TABLE EOB_EVENT;
DROP TABLE EOB_JOIN;

---------------- 생성 --------------------------------

-- 응모자 테이블 생성 
CREATE TABLE EOB_APPLICANT (
	APPLICANT_UID   NUMBER    NOT NULL -- 응모자_UID
	,NAME          VARCHAR2(100) NULL     -- 이름
	,TEL           VARCHAR2(100) NULL      -- 연락처
	,CONSTRAINT pk_EOB_APPLICANT_APPLICANT_UID PRIMARY KEY(APPLICANT_UID)
);

-- 관리자 테이블 생성 

CREATE TABLE EOB_ADMIN (
ID VARCHAR2(100) NULL 
,PASSWORD VARCHAR2(100) NULL
);

-- 이벤트 테이블 생성 

CREATE TABLE EOB_EVENT (

EVENT_UID NUMBER NOT NULL -- 이벤트 UID
,EVENT_NAME VARCHAR2(100) NULL -- 이벤트명
,START_DATE DATE NULL -- 시작일
,START_HOUR NUMBER NULL -- 시작시각
,QUANTITY NUMBER  NULL  -- 수량 

,CONSTRAINT pk_EOB_EVENT_EVENT_UID PRIMARY KEY(EVENT_UID)
);


-- 참여 테이블 생성 

CREATE TABLE EOB_JOIN (
JOIN_UID NUMBER NULL -- 참여_UID
,JOIN_TIME DATE NULL -- 신청시각
,IS_WIN NUMBER NULL -- 당첨여부 
,EVENT_UID NUMBER NULL -- 이벤트_UID(FK)
,APPLICANT_UID NUMBER NULL -- 응모자_UID(FK)
,CONSTRAINT pk_EOB_JOIN_JOIN_UID PRIMARY KEY(JOIN_UID)
);


-- 참여 FK 
ALTER TABLE EOB_JOIN
	ADD
		CONSTRAINT FK_EOB_APPLICANT_TO_EOB_JOIN -- 응모자  -> 참여
		FOREIGN KEY (APPLICANT_UID ) REFERENCES "EOB_APPLICANT" ( APPLICANT_UID);

-- 참여
ALTER TABLE EOB_JOIN
	ADD
		CONSTRAINT FK_EOB_EVENT_TO_EOB_JOIN FOREIGN KEY (EVENT_UID)
		REFERENCES EOB_EVENT ( EVENT_UID);


		
-- 시퀀스 추가        
CREATE SEQUENCE EOB_APPLICANT_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 100000;
CREATE SEQUENCE EOB_EVENT_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 100000;
CREATE SEQUENCE EOB_JOIN_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 100000;

-------------------- INSERT -------------------

INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'홍길동','010-1111-2222');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'임꺽정','010-3333-4444');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'김자바','010-5555-6666');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'오라클','010-7777-8888');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'김수정','010-9999-1010');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'문종석','010-1111-1212');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'김예일','010-1313-1414');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'이현진','010-1515-1616');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'박소희','010-1717-1818');
INSERT INTO EOB_APPLICANT (APPLICANT_UID,NAME,TEL) VALUES (EOB_APPLICANT_SEQ.NEXTVAL,'최하령','010-1919-2020');
COMMIT;

INSERT INTO EOB_ADMIN (ID, PASSWORD) VALUES ('admin', '1234');
COMMIT;


INSERT INTO EOB_EVENT (EVENT_UID, EVENT_NAME, START_DATE, START_HOUR, QUANTITY) VALUES (EOB_EVENT_SEQ.NEXTVAL, '치킨 무료 증정', TO_DATE('20180625', 'YYYYMMDD'), 15, 10);
INSERT INTO EOB_EVENT (EVENT_UID, EVENT_NAME, START_DATE, START_HOUR, QUANTITY) VALUES (EOB_EVENT_SEQ.NEXTVAL, '햄버거 무료 증정', TO_DATE('20180625', 'YYYYMMDD'), 13, 10);
INSERT INTO EOB_EVENT (EVENT_UID, EVENT_NAME, START_DATE, START_HOUR, QUANTITY) VALUES (EOB_EVENT_SEQ.NEXTVAL, '아메리카노 무료 시식', TO_DATE('20180625', 'YYYYMMDD'), 10, 10);
INSERT INTO EOB_EVENT (EVENT_UID, EVENT_NAME, START_DATE, START_HOUR, QUANTITY) VALUES (EOB_EVENT_SEQ.NEXTVAL, '무료 바캉스 쿠폰', TO_DATE('20180625', 'YYYYMMDD'), 12, 10);
INSERT INTO EOB_EVENT (EVENT_UID, EVENT_NAME, START_DATE, START_HOUR, QUANTITY) VALUES (EOB_EVENT_SEQ.NEXTVAL, '제주로 무료 이용권', TO_DATE('20180625', 'YYYYMMDD'), 11, 10);
COMMIT;
